# Generated by Django 3.0.6 on 2020-05-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('open_news', '0001_initial_fork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_news.NewsWebsite'),
        ),
    ]
